# Numpy  

In [2]:
import numpy as np # 컨트롤 시프트 마이너스로 구분 

In [13]:
a = np.array([0,1,2,3])  # 자동으로 실수형으로 바뀌는 구나 # numpy 기본은 배열 
a

array([0, 1, 2, 3])

In [14]:
np.array(a) # 이렇게 따로 넣어도 되더라 , 

array([0, 1, 2, 3])

In [17]:
a.shape 

(4,)

In [ ]:
# 8칸 바이트  0이나 1 이진수 
# 64비트 크고 좋다 이렇기 보다는 공간 낭비 , 

In [ ]:
# complex 복소수 bool  불형 , float 실수 ,  다양한 데이터 타입 들어간다 int 정수 float 실수 , complex 복소수 , 글자 uint 

In [7]:
arr1 = np.array([[1,2],[3,4]])

In [8]:
arr2 = np.array([[5,6],[7,8]])

In [ ]:
2x2x2 12 # 3차원 만들어 보자 .
    34
    56
    78

In [10]:
arr3 = np.array([ [  [ 1,2 ],[ 3 , 4] ] , [[5,6],[7,8]] ])

In [32]:
print(arr3) # 2차원 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# 이런 논리로 차원이 추가됨 . 

In [39]:
a = np.arange(1,9)
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# name 은 오브젝트를 가정해 그래서 '' 필요 

In [37]:
np.arange(4)  # 출력되는 결과물이 이미 배열을 출력해주는 함수 형태를 잘 잡아주는 것이 중요 

array([0, 1, 2, 3])

In [36]:
list(range(3))

[0, 1, 2]

In [42]:
a.reshape(2,2,2) # 모양을 바꾸어 준다 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
a= np.arange(10,22)
a.shape
a.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [50]:
a= np.arange(10,22).reshape(3,4)

In [51]:
a= np.arange(6,dtype= np.float32).reshape(2,3)

In [52]:
a= np.arange(8,dtype= np.float32).reshape(2,4)

In [55]:
a= np.arange(24).reshape(3,4,2)
a 3은 구분 되는 것들 , 큰 블럭 , 2는 열 4는 행  / 구분 행 열 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [56]:
b= np.arange(24).reshape(4,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [ ]:
(2,4) 2행4열 y x / 
(2,3,4) zyx 

In [58]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [57]:
a*3 # 3을 곱하게 됨 

array([[[ 0,  3],
        [ 6,  9],
        [12, 15],
        [18, 21]],

       [[24, 27],
        [30, 33],
        [36, 39],
        [42, 45]],

       [[48, 51],
        [54, 57],
        [60, 63],
        [66, 69]]])

In [ ]:
a = np.array([])

In [ ]:
type(a)

In [12]:
a = [1,2,3,4]
b = [5,6,7,8]

In [13]:
a+b # 리스트 

[1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
np.add(a,b) # 이게 객체 지향의 방식이다. 객체의 객채 안에 함수를 보는 것 

array([ 6,  8, 10, 12])

In [65]:
c = np.array([10,20])

In [66]:
a+c  # 한개와 내개 같이 하면 바로 복제해서 더한다.  브로드 캐스팅이라고 한다.  # 2개 수는 안되네 ?

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
np.arange()

In [ ]:
b = np.arange(3,dtype = np.float16)

In [ ]:
import numpy as np
a = np.arange(1,5).reshape(2,2)
a

In [18]:
arr1 = np.arange(1,5).reshape(2,2)
arr2= np.arange(5,9).reshape(2,2)
arr1 + arr2
arr1 * arr2 
# 행렬의 곱셈 
np.matmul(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [20]:
np.matmul(arr1,arr2)
arr1@arr2 
np.dot(arr1,arr2) # 행렬곱 


array([[19, 22],
       [43, 50]])

In [ ]:
np.arange(36).reshape(3,4,3)
a = np. arange(9,dtype = np.float32)
np.linspace(0,1,5)  #등분하기 4등분 
np.linspace(0,1,5, endpoint = False)
np.ones((3,3), int) #1로 채우기 
b = np.zeros((3,3), int) #0으로 가득
b[2,0] = 3
b # sparse matrix 희귀 행렬

In [22]:
np.diag([1,2,3]) # 대각선에 1 , 2, 3 
np.ones((3,3))*8 #숫자곱하기

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [ ]:
c = np. arange(9).reshape(3,3)
np.diag([1,2,3])
np.diag(c)
np.diag([1,1])
np.identity(2) # 단위행렬 , 
np.eye(2) # 같은 것
np.eye(3,4) # 3행 4열에서 한다 eye만 가능한 것이 잇다. 
np.tile(c,2) # repeat a 2 times
#3행 = 뒤에 것의 3뭉치
np.tile(c,(3,2)) #3행 두번 
np.full((3,3), 8) # 3행 3열 8로 가득 채운다 
np.full((4,3), 2)
np.empty((2,3))

In [ ]:
a = np.arange(6).reshape(2,3)
a
np.zeros_like(a) #껍데기는 그대로 유지한체 0으로 
b = np.arange(3,dtype = np.float16)
np.ones_like(b) # 데이터를 유지한 상태 

b[3] = 0 
b
c = a 
c[3] = 0 
c
a # C를 바꾼 이후에 ,, a 도 바뀜 

b = a[2: 4]
b[0] = 0
b
a # 바뀐다. B 는 새로 만들어 진것이 아니라 a 에 지칭을 한것 뿐 
# 카피 , 같은 객채다 . 
d = np.arange(1,9,2) # 1부터 9 2 간격 
d.shape

In [ ]:
np.arange(1,5)


/h 수평 v 수직 , 
a= np.arange(5)

np.vstack(a,a*10)
np.vstack(a,a*10,a*20,a-10)

a= np.arange(5)

np.hstack(a,a*10)
np.hstack(a,a*10,a*20,a-10)

np.dstack(a,a*10)
np.dstack(a,a*10,a*20,a-10)


a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack([a,b])
np.hstack([a,b])
np.dstack([a,b])

In [ ]:
a = np.arange(1,25).reshape((4,6))
a
A = np.vsplit(a,2) #두조각으로 

type(A)
np.array(np.vsplit(a,2)).shape

np.vsplit(a,3)   # 토막내줌 

In [ ]:
a.reshape(2,-1) # -1  자동으로 라는 뜻 
a.flatten().shape


#ravel()
b= a.ravel() # copy는 새로운 것 view는 기존것 
b[0] = 100#는

In [ ]:
a = np.arange(24).reshape(3,8)
a@ a.T 

flatten 카피
ravel view 
a.T  # 전치 행렬 

In [ ]:
A = np.array([2,1,4,3])
np.sort(A)
A
B = np.sort(A)

In [ ]:
a= [ 2,1,4,3]
np.sort(a)
a

axis = 0 은 아레로 방향 행별로 행방향  
axis = 1 x  방향  열방향 

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [ ]:
import numpy as np

np.arange
np.arange

In [ ]:
0~36개 모두 개수가 int 
36 8비트 = 1 바이트 / 인트 8 8비트씩을 저장단위로 삼아라 
내장함수는 sorted 

In [ ]:
np.arange(9).reshape(3,3,3).full(10)
np.ones((3,3,3))
배열 : *, np.multiply
행렬 : @, np.dot
객체 솔트는 뷰 넘파이 솔트는 카피 
np.arange(24).reshape(3,-1)
a[:,2] :은 처음부터 
:: 은 스탭 

In [ ]:
a = np.arange(25).reshape(5,5)

a[:,1::2]
a[4,:]
a[-1]
a[1::2,:3:2]

# 0:3:2]  : ~ 0 부터 ,3 *까지 *2 간격으로 
# 괄호 다시보기 묶어주는 이유 . 01두개 

In [ ]:
a = np.arange(0,80,10)
a
a[0]
a[ [0,1,3,5] ]

indices = [0,1,3,5]
a[indices]
a[indices] = 9 

In [ ]:
a = np.arange(36).reshape(6,6)
a
a [ [1,2]]
a[indices]
# 행이 출력 

In [ ]:
a[indices,indices]
a[:,indices]

In [ ]:
a[[0,1,2,2],[1,2,0,3]]
# and or 작동 검색할때 사용 
a = np.arange(0,80,10)
a [ a >40 ]
a [mask ]

In [ ]:
mask = (a > 40) | (a <30)
행은 20ㅂh다 크고 열은 14qㅗ다 작거나 크다. 

mask = [(a > 20 ) , (a>26)| (a<14)]

a = np.arange(25).reshape(5,5)
a[[0,1,2,3],[1,2,3,4]]
a[0:3,1:4]

In [ ]:
for i in range(0,4):
    print(a[i,i+1])
indices = [0,1,2,3]
a[indices, indices]+1

#방법2
mask_row=np.array([1,1,1,1,0], dtype=bool)
mask_col=np.array([0,1,1,1,1], dtype=bool)
a[mask_row, mask_col]
# 불 사용 트루만 출력

In [ ]:
a = np.array([1,2,3])
a+1 #  브로드 캐스팅 
b = np.array([1])
a+ b

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

np.sum(a)

np.sum(a,axis = 0 ) # 행방향
np.sum(a,axis = 1 ) #축이 0이 되도록 합치거라  # 열방향
b = np.array([[4,5,6],[1,2,3]])

np.min(a)
np.min(a, axis = 0)
np.min(a, axis = 1)

np.minimum(a,b) # 리스트가 나오네 

In [ ]:
a
a>4

a[a>4]
np.where(a>4,"H","h")  # if 와 같이 많이 씀 조건 결과 tf 

a = np.arange(-15,15).reshape(5,6)**2

np.max(a,axis=1)
np.mean(a,axis=0)

In [ ]:
64비트 = 8바이트 0해도 8바이트  
총 24바이트 / 숫자 3개가 
8바이트 9개 